name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  CONFIGURATION: 'Release'
jobs:
  build-and-test:
    name: build-and-test--${{ matrix.os-version }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      matrix:
        os-version: [windows-latest] #, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: .NET setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: .NET info
        run: dotnet --info
      - name: .NET restore
        run: dotnet restore ./src
      - name: .NET build
        run: dotnet build ./src/Dax.Template.sln --configuration ${{ env.CONFIGURATION }} --no-restore
      - name: .NET test
        run: dotnet test ./src/Dax.Template.Tests/Dax.Template.Tests.csproj --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal
      - name: .NET pack
        run: dotnet pack ./src/Dax.Template/Dax.Template.csproj --configuration ${{ env.CONFIGURATION }} --no-build --no-restore --verbosity normal